name: Cancel
# on: [push]
on:
  workflow_dispatch:    
jobs:
  cancel:
    name: 'Cancel previous runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: deep-soft/cancel-workflow-action@0.11.0
        with:
          workflow_id: "build.yml, docs-pages.yml"
          access_token: ${{ github.token }}
